<?php

namespace Sauladam\ShipmentTracker\Utils;

use Sauladam\ShipmentTracker\Track;

class StatusMapper
{
    public static function fromDescription(string $description): string
    {
        // Sanitize
        $description = str_ireplace('Packstation / DeinFach Automat', 'Packstation', $description);

        $statuses = [
            Track::STATUS_REFUSED => [
                'verweigert',
            ],
            Track::STATUS_LOCATION => [
                'Ablageort', // "Wunschort" does not appear in the status, only in the recipient field, when the package has been delivered
                'a preferred location',
            ],
            Track::STATUS_BACK       => [
                'cksendung eingeleitet',
                'Es erfolgt eine Rücksendung',
                'The shipment is being returned',
                'an den Absender zurück',
                'Rücksendung an Absender',
                'zurück zum Absender',
                'nicht in der Filiale abgeholt',
                'nicht in der Packstation abgeholt'
            ],
            Track::STATUS_DELIVERED  => [
                'Zustellung erfolgreich',
                'Abholung in der Filiale ist erfolgt',
                'Abholung aus Packstation',
                'aus der PACKSTATION abgeholt',
                'wurde aus der Packstation entnommen',
                'erfolgreich zugestellt',
                'im Rahmen der kontaktlosen Zustellung zugestellt',
                'am Wunschort abgeholt',
                'hat die Sendung in der Filiale abgeholt',
                'des Nachnahme-Betrags an den Zahlungsempf',
                'Sendung wurde zugestellt',
                'Die Sendung wurde ausgeliefert',
                'shipment has been successfully delivered',
                'recipient has picked up the shipment from the retail outlet',
                'recipient has picked up the shipment from the PACKSTATION',
                'item has been sent',
                'delivered from the delivery depot to the recipient by simplified company delivery',
                'per vereinfachter Firmenzustellung ab Eingangspaketzentrum zugestellt',
                'direkt ab Paketzentrum dem Geschäftskunden zugestellt',
            ],
            Track::STATUS_IN_TRANSIT => [
                'Einlieferung in Filiale',
                'Weiterleitung an',
                'Vorbereitung',
                'vorbereitet',
                'Weitertransport im',
                'Bearbeitung',
                'im Transitland eingetroffen',
                'In Zustellung',
                'Ankunft',
                'Transport ins',
                'Transport zum',
                'Zustellung an Packstation', // no pickup yet, in transit
                'in Packstation',
                'Weiterleitung an Filiale',
                'in das Zustellfahrzeug geladen',
                'Verladung ins Zustellfahrzeug',
                'Paketzentrum bearbeitet',
                'auf dem Weg zur PACKSTATION',
                'wird in eine PACKSTATION weitergeleitet',
                'Die Sendung wurde abgeholt',
                'Sendung wurde im Briefzentrum bearbeitet',
                'Sendung wird an die Hausadresse zugestellt',
                'wird für den Weitertransport',
                'wird für die Auslieferung',
                'im Paketzentrum eingetroffen',
                'Sendung im Weitertransport',
                'zum Weitertransport aus der PACKSTATION entnommen',
                'Zustellung in den nächsten Werktagen',
                'auf dem Weg',
                'Sendung wird ins Zielland transportiert und dort an die Zustellorganisation',
                'vom Absender in der Filiale eingeliefert',
                'Sendung konnte nicht in die PACKSTATION eingestellt werden und wurde in eine Filiale',
                'Sendung konnte nicht zugestellt werden und wird jetzt zur Abholung in die Filiale/Agentur gebracht',
                'shipment has been picked up',
                'instruction data for this shipment have been provided',
                'shipment has been processed',
                'shipment has been posted by the sender',
                'hipment has been loaded onto the delivery vehicle',
                'A 2nd attempt at delivery is being made',
                'shipment is on its way to the PACKSTATION',
                'forwarded to a PACKSTATION',
                'shipment could not be delivered to the PACKSTATION and has been forwarded to a retail outlet',
                'shipment could not be delivered, and the recipient has been notified',
                'A 2nd attempt at delivery is being made',
                'Es erfolgt ein 2. Zustellversuch',
                'Sendung wurde an DHL übergeben',
                'Sendung ist in der Region des Empfängers angekommen',
                'im Zielland/Zielgebiet eingetroffen',
                'Abholauftrag wurde zur Durchführung am nächsten Werktag',
                'Eine Nachricht wurde zugestellt',
                'wird ins Zielland/Zielgebiet transportiert',
                'Import-Paketzentrum im Zielland/Zielgebiet verlassen',
                'zur Verzollung',
                'durch den Zoll',
                'Zollabfertigung',
                'im Start-Paketzentrum eingetroffen',
                'Die Sendung wird bearbeitet',
                'wurde zur Zustellung übergeben',
                'Export-Paketzentrum eingetroffen',
                'Abholung erfolgreich',
                'Abholung wurde erfolgreich',
                'Auslands-Sendung an DHL übergeben',
                'Sendung wird an die gewünschte',
                'prepared for onward transport',
                'im Zustell-Depot bearbeitet',
                'Sendung ist mit Flug',
            ],
            Track::STATUS_PICKUP     => [
                'Die Sendung liegt in der',
                'Die Sendung liegt zur Abholung',
                'liegt in der Filiale zur Abholung',
                'in der Filiale hinterlegt',
                'Die Sendung liegt in der PACKSTATION',
                'Die Sendung liegt ab sofort in der',
                'Uhrzeit der Abholung kann der Benachrichtigungskarte entnommen werden',
                'earliest time when it can be picked up can be found on the notification card',
                'shipment is ready for pick-up at the PACKSTATION',
                'Sendung wird zur Abholung in die',
                'Sendung wurde zur Abholung in die',
                'wurde in eine Filiale weitergeleitet',
                'wurde an eine Hauspoststelle weitergeleitet',
                'The shipment is being brought to',
                'beim Zoll abholen',
                'liegt für den Empfänger zur Abholung bereit',
                'In Kürze in Filiale abholbereit',
                'am nächsten Werktag in Filiale abholbereit',
                'ist voraussichtlich in Kürze abholbereit',
            ],
            Track::STATUS_DIGITAL    => [
                'elektronisch an',
            ],
            Track::STATUS_INFO       => [
                'Neue Zustellanschrift',
                'wurde gewählt',
                'vorgemerkt',
                'als neue Lieferadresse gewählt',
                'wird die Sendung an eine neue Empfängeradresse gesandt',
                'wird bei uns gelagert',
                'erneuter Zustellversuch am nächsten Werktag',
                'Zustellung am nächsten Werktag',
                'Wunsch des Empfängers',
                'wurde vom Absender in die Packstation eingeliefert',
                'Abgang der Sendung aus der Paketermittlung',
                'gebucht',
                'Flugzeug',
                'Lufttransport',
                'Weiterleitung an neue Empfängeradresse',
                'neue Adresse des Empfängers weitergeleitet',
                'wurde als Zustelladresse gewählt',
                'im Ursprungsland freigegeben',
                'Freigabe der Sendung im Ursprungsland',
            ],
            Track::STATUS_WARNING    => [
                'Verzögerte Zustellung',
                'Zweiter Zustellversuch erfolglos',
                'Zur Abholung benötigte Benachrichtigungskarte wird per Brief zugestellt',
                'Sendung konnte nicht zugestellt werden',
                'Zustellversuch nicht zugestellt werden',
                'heute leider nicht zugestellt werden',
                'nicht zugestellt werden. Die Sendung wird voraussichtlich',
                'Sendung wurde leider fehlgeleitet',
                'Sendung wurde zurückgestellt',
                'Sendung verzögert sich',
                'aufgrund höherer Gewalt',
                'nicht möglich',
                'nicht erfolgreich',
                'nicht gefunden',
                'geschlossen',
                'nachverpackt',
                'neu verpackt',
                'Neuverpackung',
                'Sendung wurde beschädigt',
                'beschädigte Sendung',
                'shipment could not be delivered',
                'attempting to obtain a new delivery address',
                'eine neue Zustelladresse für den Empf',
                'Sendung wurde fehlgeleitet und konnte nicht zugestellt werden. Die Sendung wird umadressiert und an den',
                'shipment was misrouted and could not be delivered. The shipment will be readdressed and forwarded to the recipient',
                'höhere Gewalt',
                'gewünschte Liefertag wurde storniert',
                'konnte leider nicht in die gewünschte Packstation eingestellt werden',
                'Empfänger wurde nicht angetroffen',
                'Aufgrund eines Nachsendeauftrags',
                'Aufgrund einer Beschädigung',
                'aufgrund Beschädigung',
                'Nachverpackungsstelle',
                'in der Nachverpackung von DHL bearbeitet',
                'Zustellversuch erfolgt am nächsten Werktag',
                'Zustellversuch am nächsten Werktag',
                'konnte nicht in die gewünschte Packstation eingestellt werden',
                'konnte nicht in die Packstation eingestellt werden und wird in die Filiale',
            ],
            Track::STATUS_EXCEPTION  => [
                'Aufgrund fehlender Adressangaben wird aktuell der Empfänger der Sendung ermittelt',
                'Lagerfrist überschritten',
                'Paketstopp',
                'Adressfehlers konnte die Sendung nicht zugestellt',
                'Zustelladresse nicht angefahren',
                'entspricht nicht den Versandbedingungen',
                'nicht unseren Versandbedingungen',
                'nger unbekannt',
                'nger ist unbekannt',
                'The address is incomplete',
                'ist falsch',
                'is incorrect',
                'recipient has not picked up the shipment',
                'Es erfolgte keine Einlieferung zu der per EDI Daten beauftragten Sendung',
                'leeres Fach in Packstation vorgefunden',
                'Paketermittlung',
                'Sendung ist beschädigt',
                'Versandbedingungen nicht erfüllt',
                'Ermittlung Empfängeradresse',
                'zum Absender zurückgesendet',
            ],
        ];

        foreach ($statuses as $status => $needles) {
            foreach ($needles as $needle) {
                if (stripos($description, $needle) !== false) {
                    return $status;
                }
            }
        }

        return Track::STATUS_UNKNOWN;
    }
}
